### ISSUE TITLE
Addigy Script - Incorrect organization key using the POLICY_PATH variable if there is whitespace

### ISSUE THREAD

**Issue by koilosa** [huntresslabs/deployment-scripts#89]
Seems that if the top level policy name in Addigy contains any spaces, the install script only sees the first word in the name and then uses that as the organization key during installation. For example, a top level policy "ACME Corp" gets installed to the organization "ACME" in huntress, rather than the correct "ACME Corp". 

I confirmed in the log files that the whole policy name is showing up in the "Provided Organization Key" line item, but still has whitespace in it rather than dashes as would be expected for an organization key copied from the huntress.io console.

**Comment by uttie-huntress** [comment]
hey @koilosa !
Thanks for reaching out. Assuming this was a bug that was affecting macOS Addigy deployments, we've fixed this issue in #88 and released a new version of the script.
That should fix it. Can you try that out and see if it addresses your issue?

**Comment by koilosa** [comment]
hi @uttie-huntress - sorry for the delay but the new script works and fixes this issue when deploying through Addigy. Thank you for the fix!
